---
title: YOUR TITLE
author: YOUR NAME
date: Month date, YEAR
output: 
  revealjs::revealjs_presentation:
    pandoc_args: [ "--slide-level", "2" ]
    self_contained: false
    reveal_plugins: ["menu","notes"]
    reveal_options:
      slideNumber: true
      menu:
        numbers: true
    transition: "fade"
    theme: night
    highlight: pygments
    css: styles.css
    center: true
---

# This style will set background for all slides
You have to balance the `'background-color:black'` in this style to that of `'theme: night'` in YAML..
  
If your background image contain `text`..it's color should be in contrast to the `'background-color:black'`..
<style>
body {
   background: url( "fig/IPB-University-white.svg" ) no-repeat;
   background-position: top 25px left 50px;
   background-color:black;
   background-size:150px;
   opacity:1;
   z-index:1;
}
</style>

## If you opt to set background for a particular slide..you can tag it as this.. {data-background="fig/IPB-University-white.svg" data-background-size="120px" data-background-position="top 25px right 50px"}
- you have to position this image so it won't overlap with the all-slide background..
- or..you may want to delete the all-slide background..

# You have a menu..
..click the three-horizontal-bar on the bottom-left..

# You can have notes..
..try click »S« key to open the *notes* window..  

<div class="notes">
..but notes plugin inhibit you to do self_contained: true

- It can contain markdown
- like this list
</div>
